module.exports = {
  apps: [
    {
      name: "dental-strapi",
      cwd: "/home/ec2-user/dental-app/strapi-cms",
      script: "./node_modules/.bin/strapi",
      args: "start",
      env: {
        NODE_ENV: "production",
        HOST: "0.0.0.0",
        PORT: 1337,
        DATABASE_CLIENT: "postgres",
        DATABASE_HOST: "localhost",
        DATABASE_PORT: 5433,
        DATABASE_NAME: "dental_cms_strapi",
        DATABASE_USERNAME: "postgres",
        DATABASE_PASSWORD: "postgres",
        DATABASE_SSL: "false",
        DATABASE_SCHEMA: "public",
        APP_KEYS: process.env.APP_KEYS,
        API_TOKEN_SALT: process.env.API_TOKEN_SALT,
        ADMIN_JWT_SECRET: process.env.ADMIN_JWT_SECRET,
        TRANSFER_TOKEN_SALT: process.env.TRANSFER_TOKEN_SALT,
        JWT_SECRET: process.env.JWT_SECRET,
        PUBLIC_URL: "https://nhakhoaquoctesaigon.ddns.net",
        FRONTEND_URL: "https://nhakhoaquoctesaigon.ddns.net",
        PREVIEW_SECRET: process.env.PREVIEW_SECRET,
        STRAPI_WEBHOOK_SECRET:
          process.env.STRAPI_WEBHOOK_SECRET,
        NEXTJS_URL: "https://nhakhoaquoctesaigon.ddns.net",
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
    },
    {
      name: "dental-frontend",
      cwd: "/home/ec2-user/dental-app/dental-frontend",
      script: "./node_modules/.bin/next",
      args: "start -p 3003",
      env: {
        NODE_ENV: "production",
        PORT: 3003,
        NEXT_PUBLIC_SERVER_URL: "https://nhakhoaquoctesaigon.ddns.net",
        STRAPI_URL: "http://localhost:1337",
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN,
        NEXT_PREVIEW_SECRET: "your-secure-preview-secret-change-in-production",
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
    },
  ],
};
