import Image from 'next/image'
import Link from 'next/link'
import { MotionFaqAccordion } from '@/src/components/ui/motion-faq-accordion'

type Block = { blockType: string; [key: string]: any }

const shell = 'mx-auto max-w-home-container px-4 py-20 sm:px-6 lg:px-8'
const heading = 'text-3xl font-bold tracking-tight text-smilux-text sm:text-4xl'

function Media({ image, alt }: { image?: any; alt: string }) {
  if (!image?.url) return <div className="flex aspect-[4/3] items-center justify-center rounded-2xl bg-surface-blue text-sm text-smilux-muted">DR. MARIS AESTHETICS care</div>
  return <div className="relative aspect-[4/3] overflow-hidden rounded-2xl bg-surface-blue"><Image src={image.url} alt={image.alt || alt} fill sizes="(max-width: 768px) 100vw, 40vw" className="object-cover" /></div>
}

function SectionHeading({ data }: { data: Block }) {
  return <header className="max-w-2xl"><p className="eyebrow">{data.eyebrow || 'DR. MARIS AESTHETICS'}</p><h2 className={`${heading} mt-3`}>{data.title || data.heading || 'Specialist cosmetic surgery care'}</h2>{data.subtitle && <p className="mt-4 text-smilux-body leading-7">{data.subtitle}</p>}</header>
}

export function HomepageLegacyUiSection({ data }: { data: Block }) {
  if (data.blockType === 'about') return <section className="bg-surface-subtle"><div className={`${shell} grid gap-10 lg:grid-cols-2 lg:items-center`}><div><SectionHeading data={data} /><div className="mt-6 whitespace-pre-line leading-7 text-smilux-body">{data.content}</div></div><Media image={data.image} alt={data.title} /></div></section>
  if (data.blockType === 'services') return <section className="bg-white"><div className={shell}><SectionHeading data={data} /><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{(data.items || []).map((item: any, i: number) => <article key={item.id || i} className="rounded-2xl border border-smilux-border bg-white p-6 shadow-card"><div className="mb-5 flex h-10 w-10 items-center justify-center rounded-xl bg-surface-blue text-smilux-primary">0{i + 1}</div><h3 className="font-bold text-smilux-text">{item.title}</h3><p className="mt-2 text-sm leading-6 text-smilux-body">{item.description}</p>{item.link && <Link href={item.link} className="mt-4 inline-block text-sm font-semibold text-smilux-primary">Learn more →</Link>}</article>)}</div></div></section>
  if (data.blockType === 'trust') return <section className="bg-surface-subtle"><div className={shell}><SectionHeading data={data} /><div className="mt-10 grid grid-cols-2 gap-4 lg:grid-cols-4">{(data.stats || []).map((item: any, i: number) => <div key={item.id || i} className="rounded-2xl border border-smilux-border bg-white p-5"><strong className="text-3xl font-bold text-smilux-navy">{item.number}{item.suffix}</strong><p className="mt-2 text-sm text-smilux-body">{item.label}</p></div>)}</div></div></section>
  if (data.blockType === 'doctor') return <section className="bg-white"><div className={shell}><SectionHeading data={data} /><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{(data.doctors || []).map((doctor: any, i: number) => <article key={doctor.id || i} className="overflow-hidden rounded-2xl border border-smilux-border bg-white shadow-card"><Media image={doctor.image} alt={doctor.name} /><div className="p-5"><h3 className="font-bold text-smilux-text">{doctor.name}</h3><p className="mt-1 text-sm font-medium text-smilux-primary">{doctor.specialization}</p>{doctor.bio && <p className="mt-3 text-sm leading-6 text-smilux-body">{doctor.bio}</p>}</div></article>)}</div></div></section>
  if (data.blockType === 'certification') return <section className="bg-surface-subtle"><div className={shell}><SectionHeading data={data} /><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{(data.certificates || []).map((cert: any, i: number) => <article key={cert.id || i} className="rounded-2xl border border-smilux-border bg-white p-5 shadow-card"><Media image={cert.image} alt={cert.name} /><h3 className="mt-4 font-bold text-smilux-text">{cert.name}</h3>{cert.organization && <p className="mt-1 text-sm text-smilux-body">{cert.organization}</p>}</article>)}</div></div></section>
  if (data.blockType === 'combined-testimonial-result' || data.blockType === 'testimonials') return <section className="bg-white"><div className={shell}><SectionHeading data={data} /><div className="mt-10 grid gap-4 md:grid-cols-3">{(data.items || []).map((item: any, i: number) => <figure key={item.id || i} className="rounded-2xl border border-smilux-border bg-surface-subtle p-6"><div className="text-rating-star">★★★★★</div><blockquote className="mt-4 leading-7 text-smilux-body">“{item.content || item.quote}”</blockquote><figcaption className="mt-5 font-semibold text-smilux-text">{item.customerName || item.name || item.authorName}</figcaption></figure>)}</div></div></section>
  if (data.blockType === 'process') return <section className="bg-surface-blue"><div className={shell}><SectionHeading data={data} /><div className="mt-10 grid gap-4 md:grid-cols-3">{(data.steps || []).map((step: any, i: number) => <article key={step.id || i} className="rounded-2xl bg-white p-6 shadow-card"><span className="text-sm font-bold text-smilux-primary">0{i + 1}</span><h3 className="mt-4 font-bold text-smilux-text">{step.title}</h3><p className="mt-2 text-sm leading-6 text-smilux-body">{step.description}</p></article>)}</div></div></section>
  if (data.blockType === 'faq') return <section className="bg-white"><div className={shell}><SectionHeading data={data} /><MotionFaqAccordion className="mt-8 grid gap-3" itemClassName="rounded-xl border border-smilux-border p-5" items={(data.questions || []).map((q: any, i: number) => ({ id: q.id || i, question: q.question, answer: q.answer }))} /></div></section>
  if (data.blockType === 'blog-collection-section') return <section className="bg-surface-subtle"><div className={shell}><SectionHeading data={data} /><div className="mt-10 grid gap-5 md:grid-cols-3">{(data.posts || []).map((post: any, i: number) => { const item = post.attributes || post; return <article key={post.id || i} className="rounded-2xl border border-smilux-border bg-white p-5 shadow-card"><Media image={item.coverImage} alt={item.title} /><p className="mt-4 text-xs font-semibold uppercase tracking-wider text-smilux-primary">SmileLux Journal</p><h3 className="mt-2 font-bold text-smilux-text">{item.title}</h3>{item.excerpt && <p className="mt-2 text-sm leading-6 text-smilux-body">{item.excerpt}</p>}</article> })}</div></div></section>
  if (data.blockType === 'papers-section') return <section className="bg-white"><div className={shell}><SectionHeading data={data} /><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{(data.papers || []).map((paper: any, i: number) => <Link key={paper.id || i} href={paper.link || '#'} className="block"><Media image={paper.image} alt="SmileLux clinical result" /></Link>)}</div></div></section>
  if (data.blockType === 'cta') return <section className="bg-smilux-navy-dark text-white"><div className={`${shell} flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between`}><div><p className="eyebrow text-smilux-sky">Free consultation</p><h2 className="mt-3 text-3xl font-bold">{data.heading}</h2>{(data.subheading || data.text) && <p className="mt-3 max-w-2xl text-blue-100">{data.subheading || data.text}</p>}</div>{(data.buttonLink || data.button_link) && <Link href={data.buttonLink || data.button_link} className="inline-flex min-h-12 shrink-0 items-center justify-center rounded-xl bg-white px-6 font-semibold text-smilux-navy-dark">{data.buttonLabel || data.button_label || 'Book a consultation'}</Link>}</div></section>
  return null
}
