import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        'smilux-primary': 'var(--smilux-primary)',
        'smilux-hero-primary': 'var(--smilux-hero-primary)',
        'smilux-badge': 'var(--smilux-badge)',
        'smilux-hero-accent': 'var(--smilux-hero-accent)',
        'smilux-primary-hover': 'var(--smilux-primary-hover)',
        'smilux-primary-soft': 'var(--smilux-primary-soft)',
        'smilux-navy': 'var(--smilux-navy)',
        'smilux-navy-dark': 'var(--smilux-navy-dark)',
        'smilux-sky': 'var(--smilux-sky)',
        'smilux-text': 'var(--smilux-text)',
        'smilux-body': 'var(--smilux-body)',
        'smilux-muted': 'var(--smilux-muted)',
        'smilux-border': 'var(--smilux-border)',
        'surface-subtle': 'var(--smilux-surface-subtle)',
        'surface-blue': 'var(--smilux-surface-blue)',
        'rating-star': 'var(--smilux-rating-star)',
        background: "var(--color-background)",
        foreground: "var(--color-foreground)",
        "foreground-secondary": "var(--color-foreground-secondary)",
        primary: {
          50: "var(--color-primary-50)",
          100: "var(--color-primary-100)",
          200: "var(--color-primary-200)",
          300: "var(--color-primary-300)",
          400: "var(--color-primary-400)",
          500: "var(--color-primary-500)",
          600: "var(--color-primary-600)",
          700: "var(--color-primary-700)",
          800: "var(--color-primary-800)",
          900: "var(--color-primary-900)",
          950: "var(--color-primary-950)",
        },
        secondary: {
          50: "var(--color-secondary-50)",
          100: "var(--color-secondary-100)",
          200: "var(--color-secondary-200)",
          300: "var(--color-secondary-300)",
          400: "var(--color-secondary-400)",
          500: "var(--color-secondary-500)",
          600: "var(--color-secondary-600)",
          700: "var(--color-secondary-700)",
          800: "var(--color-secondary-800)",
          900: "var(--color-secondary-900)",
          950: "var(--color-secondary-950)",
        },
        neutral: {
          50: "var(--color-neutral-50)",
          100: "var(--color-neutral-100)",
          200: "var(--color-neutral-200)",
          300: "var(--color-neutral-300)",
          400: "var(--color-neutral-400)",
          500: "var(--color-neutral-500)",
          600: "var(--color-neutral-600)",
          700: "var(--color-neutral-700)",
          800: "var(--color-neutral-800)",
          900: "var(--color-neutral-900)",
          950: "var(--color-neutral-950)",
        },
        gray: {
          50: "var(--color-neutral-50)",
          100: "var(--color-neutral-100)",
          200: "var(--color-neutral-200)",
          300: "var(--color-neutral-300)",
          400: "var(--color-neutral-400)",
          500: "var(--color-neutral-500)",
          600: "var(--color-neutral-600)",
          700: "var(--color-neutral-700)",
          800: "var(--color-neutral-800)",
          900: "var(--color-neutral-900)",
          950: "var(--color-neutral-950)",
        },
        slate: {
          50: "var(--color-neutral-50)",
          100: "var(--color-neutral-100)",
          200: "var(--color-neutral-200)",
          300: "var(--color-neutral-300)",
          400: "var(--color-neutral-400)",
          500: "var(--color-neutral-500)",
          600: "var(--color-neutral-600)",
          700: "var(--color-neutral-700)",
          800: "var(--color-neutral-800)",
          900: "var(--color-neutral-900)",
          950: "var(--color-neutral-950)",
        },
        destructive: {
          50: "var(--color-destructive-50)",
          500: "var(--color-destructive-500)",
          600: "var(--color-destructive-600)",
          foreground: "var(--color-destructive-foreground)",
        },
        success: {
          50: "var(--color-success-50)",
          500: "var(--color-success-500)",
          600: "var(--color-success-600)",
          foreground: "var(--color-success-foreground)",
        },
        warning: {
          50: "var(--color-warning-50)",
          500: "var(--color-warning-500)",
          600: "var(--color-warning-600)",
          foreground: "var(--color-warning-foreground)",
        },
        border: "var(--color-border)",
        ring: "var(--color-ring)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        hero: "var(--radius-hero)",
        full: "var(--radius-full)",
      },
      letterSpacing: {
        badge: "var(--smilux-badge-tracking)",
      },
      maxWidth: { 'home-container': '1240px' },
      boxShadow: { card: '0 6px 24px rgba(10,45,95,.06)', 'card-hover': '0 10px 30px rgba(10,45,95,.10)' },
      backgroundImage: {
        'hero-button': 'var(--smilux-hero-button-gradient)',
        'technology-button': 'var(--smilux-technology-button-gradient)',
      },
      fontFamily: {
        sans: [
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          '"Helvetica Neue"',
          "Arial",
          '"Noto Sans"',
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      animation: {
        shimmer: "shimmer 2s infinite",
      },
      keyframes: {
        shimmer: {
          "100%": { transform: "translateX(100%)" },
        },
      },
    },
  },
  plugins: [],
};
export default config;
